swagger: "2.0"
info:
  description: Family Tree API to track people and the connections between them
  version: "0.1"
  title: Family Tree API
consumes:
  - application/json
produces:
  - application/json

basePath: /api

paths:
  /people:
    get:
      operationId: family_tree.views.people.read_all
      tags:
        - People
      summary: Read the entire set of people, sorted by last name
      description: Read the entire set of people, sorted by last name
      responses:
        200:
          description: Successfully read people set operation
          schema:
            type: array
            items:
              properties:
                person_id:
                  type: integer
                  description: Id of the person
                first_name:
                  type: string
                  description: First name of the person
                last_name:
                  type: string
                  description: Last name of the person
                phone_number:
                  type: string
                  description: Phone Number of the person
                email:
                  type: string
                  description: Email Address of the person
                address:
                  type: string
                  description: Address of the person
                birth_date:
                  type: string
                  description: Birth Date of the person
                timestamp:
                  type: string
                  description: Create timestamp of the person

    post:
      operationId: family_tree.views.people.create
      tags:
        - People
      summary: Create a person
      description: Create a person
      parameters:
        - name: person
          in: body
          description: Person to create
          required: True
          schema:
            type: object
            properties:
              first_name:
                type: string
                description: First name of the person
              last_name:
                type: string
                description: Last name of the person
              phone_number:
                type: string
                description: Phone Number of the person
              email:
                type: string
                description: Email Address of the person
              address:
                type: string
                description: Address of the person
              birth_date:
                type: string
                description: Birth Date of the person
      responses:
        201:
          description: Successfully created person
          schema:
            properties:
              person_id:
                type: integer
                description: Id of the person
              first_name:
                type: string
                description: First name of the person
              last_name:
                type: string
                description: Last name of the person
              phone_number:
                type: string
                description: Phone Number of the person
              email:
                type: string
                description: Email Address of the person
              address:
                type: string
                description: Address of the person
              birth_date:
                type: string
                description: Birth Date of the person
              timestamp:
                type: string
                description: Create timestamp of the person

  /people/{last_name}:
    get:
      operationId: family_tree.views.people.read_one
      tags:
        - People
      summary: Read a person
      description: Read a person
      parameters:
        - name: last_name
          in: path
          description: Last name of the person to get from the list
          type: string
          required: True
      responses:
        200:
          description: Successfully read person from people list operation
          schema:
            properties:
              person_id:
                type: integer
                description: Id of the person
              first_name:
                type: string
                description: First name of the person
              last_name:
                type: string
                description: Last name of the person
              phone_number:
                type: string
                description: Phone Number of the person
              email:
                type: string
                description: Email Address of the person
              address:
                type: string
                description: Address of the person
              birth_date:
                type: string
                description: Birth Date of the person
              timestamp:
                type: string
                description: Create timestamp of the person

    put:
      operationId: family_tree.views.people.update
      tags:
        - People
      summary: Update a person in the people list
      description: Update a person in the people list
      parameters:
        - name: last_name
          in: path
          description: Last name of the person to get from the list
          type: string
          required: True
        - name: person
          in: body
          schema:
            type: object
            properties:
              first_name:
                type: string
                description: First name of the person
              last_name:
                type: string
                description: Last name of the person
              phone_number:
                type: string
                description: Phone Number of the person
              email:
                type: string
                description: Email Address of the person
              address:
                type: string
                description: Address of the person
              birth_date:
                type: string
                description: Birth Date of the person
      responses:
        200:
          description: Successfully updated person in people list operation

    delete:
      operationId: family_tree.views.people.delete
      tags:
        - People
      summary: Delete a person frpm the people list
      description: Delete a person from the people list
      parameters:
        - name: last_name
          in: path
          description: Last name of the person to delete from the list
          type: string
          required: True
      responses:
        200:
          description: Successfully deleted person in people list operation
